apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.9.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false

# Elasticsearch: для хранения и поиска логов.